// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Fs = require("fs");
var Belt_Array = require("rescript/lib/js/belt_Array.js");
var Belt_SetString = require("rescript/lib/js/belt_SetString.js");

var input = Fs.readFileSync("input/Week1/Year2020Day6.sample.txt", "utf8");

function splitStr(arr, srt) {
  return arr.split(srt);
}

function makeGroups(input) {
  return Belt_Array.map(input.split("\n\n"), (function (str) {
                return str.split("\n");
              }));
}

function setArray(arr) {
  return Belt_SetString.fromArray(Belt_Array.concatMany(Belt_Array.map(arr, (function (str) {
                        return str.split("");
                      }))));
}

function countAnswers(input) {
  return Belt_Array.reduce(Belt_Array.map(Belt_Array.map(makeGroups(input), setArray), Belt_SetString.size), 0, (function (acc, value) {
                return acc + value | 0;
              }));
}

console.log(countAnswers(input));

exports.input = input;
exports.splitStr = splitStr;
exports.makeGroups = makeGroups;
exports.setArray = setArray;
exports.countAnswers = countAnswers;
/* input Not a pure module */
