// Generated by ReScript, PLEASE EDIT WITH CARE
"use strict";

var hyo = {
  age: 10
};

console.log(hyo);

var hyojeong = {
  name: "hyojeong",
  age: 20,
  school: "A university"
};

var new_Hyojeong = {
  name: "hyojeong",
  age: 20,
  school: "C university"
};

console.log(hyojeong);

console.log(new_Hyojeong);

var susan = {
  name: "susan",
  age: 20,
  school: "B university"
};

exports.hyo = hyo;
exports.hyojeong = hyojeong;
exports.susan = susan;
exports.new_Hyojeong = new_Hyojeong;
/*  Not a pure module */
