// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var myTuple = [
  1,
  "hello"
];

console.log(myTuple);

var tuple = [
  1,
  3,
  5.2
];

console.log(tuple);

var my_str = "hello";

var stringType = "hello";

console.log(3);

console.log(5);

console.log(stringType);

console.log([
      5,
      my_str
    ]);

var my_tuple = [
  5,
  "hello"
];

var y = 3;

var intType = 5;

var my_int = 5;

exports.myTuple = myTuple;
exports.my_tuple = my_tuple;
exports.tuple = tuple;
exports.y = y;
exports.intType = intType;
exports.stringType = stringType;
exports.my_int = my_int;
exports.my_str = my_str;
/*  Not a pure module */
