// Generated by ReScript, PLEASE EDIT WITH CARE
"use strict";

var weather_to_feeling = "happy";

console.log(weather_to_feeling);

var weather_to_feeling$1 = "sad";

console.log(weather_to_feeling$1);

var my_option = "hello world";

var tell_me_my_value =
  my_option !== undefined ? my_option : "You didn't give me a string";

var tell_me_my_value2 = "You didn't give me a string";

console.log(tell_me_my_value);

console.log(tell_me_my_value2);

var current_weather = /* Rainy */ 1;

var my_option2;

exports.current_weather = current_weather;
exports.weather_to_feeling = weather_to_feeling$1;
exports.my_option = my_option;
exports.my_option2 = my_option2;
exports.tell_me_my_value = tell_me_my_value;
exports.tell_me_my_value2 = tell_me_my_value2;
/*  Not a pure module */
